apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: liqo-node-label-resource-plugin-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - list
  - watch
