apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: liqo-node-label-resource-plugin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: liqo-node-label-resource-plugin-role
subjects:
- kind: ServiceAccount
  name: liqo-node-labels-resource-plugin-sa
  namespace: liqo