apiVersion: v1
kind: Service
metadata:
  name: liqo-node-labels-resources-plugin
spec:
  ports:
  - name: grpc-api
    port: 6001
    protocol: TCP
    targetPort: grpc-api
  selector:
      app.kubernetes.io/name: liqo-resource-plugins
      app.kubernetes.io/instance: external-monitor-node-labels-resources
      app.kubernetes.io/component: plugin
      app.kubernetes.io/part-of: liqo
      app.kubernetes.io/managed-by: manual
  type: ClusterIP